#include "DSP2833x_Device.h"

/**
 * Author: Shaffebd
 * Last revision: 3/15/17
 */


/**
 * Start off by setting up the system. This essentially means setting specific registers to specific values.
 * These registers control device operational states, such as what mode the ADC is in, how various MUXes are configured,
 * and what the GPIO is doing. The main board, referred to as the Control Card, communicates to the Peripheral Explorer board via
 * the GPIO, which makes programming the Control Card simultaneously simple and very confusing.
 */

void InitSystem(void); //Setup the main system
void GPIOSetup(void);  //Setup the GPIO
void delay_loop(long); //Just a nice delay system
void set_bit(Uint16);

/*
 *
 */
void main(void) {
	
    InitSystem();   //Initialize the system as described below.
    DINT;           //Disable all interrupt flags.
    GPIOSetup();    //Initialize the GPIO as described below.

    //=====================
    //Custom code
    //=====================

    Uint16 mode = 1;
    Uint16 counter = 0;

    while (1){

        switch(mode){
        case 1:
            counter = (counter == 0) ? 1 : counter << 1;
            if(counter == 1) set_bit(counter);
            if(counter == 2) set_bit(counter);
            if(counter == 4) set_bit(counter);
            if(counter == 8) set_bit(counter);
            counter = (counter == 8) ? 0 : counter;
            break;
        case 2:
            counter++;
            if(counter&1) GpioDataRegs.GPASET.bit.GPIO9 = 1;
                else GpioDataRegs.GPACLEAR.bit.GPIO9 = 1;
            if(counter&2) GpioDataRegs.GPASET.bit.GPIO11 = 1;
                else GpioDataRegs.GPACLEAR.bit.GPIO11 = 1;
            if(counter&4) GpioDataRegs.GPBSET.bit.GPIO34 = 1;
                else GpioDataRegs.GPBCLEAR.bit.GPIO34 = 1;
            if(counter&8) GpioDataRegs.GPBSET.bit.GPIO49 = 1;
                else GpioDataRegs.GPBCLEAR.bit.GPIO49 = 1;
            break;
        default:
            GpioDataRegs.GPBCLEAR.bit.GPIO34 = 1;
            GpioDataRegs.GPACLEAR.bit.GPIO11 = 1;
            GpioDataRegs.GPACLEAR.bit.GPIO9 = 1;
            GpioDataRegs.GPBCLEAR.bit.GPIO49 = 1;
            break;
        }

        delay_loop(1000000);

    }

    //=====================
    //End of custom code
    //=====================

	return;
}

void set_bit(Uint16 counter){

    switch(counter){
    case 1:
        GpioDataRegs.GPASET.bit.GPIO9 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO11 = 1;
        GpioDataRegs.GPBCLEAR.bit.GPIO34 = 1;
        GpioDataRegs.GPBCLEAR.bit.GPIO49 = 1;
        break;
    case 2:
        GpioDataRegs.GPASET.bit.GPIO11 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO9 = 1;
        GpioDataRegs.GPBCLEAR.bit.GPIO34 = 1;
        GpioDataRegs.GPBCLEAR.bit.GPIO49 = 1;
        break;
    case 4:
        GpioDataRegs.GPBSET.bit.GPIO34 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO11 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO9 = 1;
        GpioDataRegs.GPBCLEAR.bit.GPIO49 = 1;
        break;
    case 8:
        GpioDataRegs.GPBSET.bit.GPIO49 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO11 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO9 = 1;
        GpioDataRegs.GPBCLEAR.bit.GPIO34 = 1;
        break;
    default:
        GpioDataRegs.GPBCLEAR.bit.GPIO34 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO11 = 1;
        GpioDataRegs.GPACLEAR.bit.GPIO9 = 1;
        GpioDataRegs.GPBCLEAR.bit.GPIO49 = 1;
        break;
    }

}

/**
 * Like I said, it's all just register assignments, but the labels are sometimes very vague.
 * Cheat sheet:
 * PLL: Phase locked loop. Takes the slow clock (external, generated by an oscillator) and makes it fast.
 * PLLCR: PLL Control Register. Controls the output of the PLL.
 * HISPCP/LOSPCP: High/Low-speed clock prescaler. Scales the output clock from the CPU for use by some peripherals.
 * PCLKCRx: Peripheral Clock Control Register: Controls whether a peripheral receives a clock signal (enables or disables that peripheral).
 *      Each bit in each PCLKCR controls an individual peripheral.
 *
 * Borrowed InitSystem, GPIOSetup and delay_loop from a lab solution written by Frank Bormann in 2009.
 */

void delay_loop(long end)
{
    long i;
    for (i = 0; i < end; i++)
    {
        asm(" NOP");
        EALLOW;
        SysCtrlRegs.WDKEY = 0x55;
        SysCtrlRegs.WDKEY = 0xAA;
        EDIS;
    }
}

void InitSystem(void)
{
    /**
     * How do I determine the hex values to set? Determine which peripherals are needed. Convert the binary register
     * values into hex. Done.
     */
    EALLOW; //Assembly command to... ?
    SysCtrlRegs.WDCR = 0x0028;          // Watchdog enabled, 4.3 milliseconds
    SysCtrlRegs.PLLSTS.bit.DIVSEL = 2;
    SysCtrlRegs.PLLCR.bit.DIV = 10;     // 30MHz * 10 / 2 = 150 MHz
    SysCtrlRegs.HISPCP.all = 0x0001;    //1/2 Sys clock speed
    SysCtrlRegs.LOSPCP.all = 0x0002;    //1/4 Sys clock speed
    SysCtrlRegs.PCLKCR0.all = 0x0000;   //Peripherals disabled
    SysCtrlRegs.PCLKCR1.all = 0x0000;   //Peripherals disabled
    SysCtrlRegs.PCLKCR3.all = 0x0000;   //Peripherals disabled
    SysCtrlRegs.PCLKCR3.bit.GPIOINENCLK = 1; //GPIO Input Enable Clock?
    EDIS; //Assembly command to do the opposite of the previous one.
}

void GPIOSetup(void)
{
    EALLOW;
    GpioCtrlRegs.GPAMUX1.all = 0;       // GPIO15 ... GPIO0 = General Purpose I/O
    GpioCtrlRegs.GPAMUX2.all = 0;       // GPIO31 ... GPIO16 = General Purpose I/O
    GpioCtrlRegs.GPBMUX1.all = 0;       // GPIO47 ... GPIO32 = General Purpose I/O
    GpioCtrlRegs.GPBMUX2.all = 0;       // GPIO63 ... GPIO48 = General Purpose I/O
    GpioCtrlRegs.GPCMUX1.all = 0;       // GPIO79 ... GPIO64 = General Purpose I/O
    GpioCtrlRegs.GPCMUX2.all = 0;       // GPIO87 ... GPIO80 = General Purpose I/O

    GpioCtrlRegs.GPADIR.all = 0;        // Set GPIO 31-0 to defaults
    GpioCtrlRegs.GPADIR.bit.GPIO9 = 1;  // peripheral explorer: LED LD1 at GPIO9
    GpioCtrlRegs.GPADIR.bit.GPIO11 = 1; // peripheral explorer: LED LD2 at GPIO11

    GpioCtrlRegs.GPBDIR.all = 0;        // Set GPIO 63-32 to defaults
    GpioCtrlRegs.GPBDIR.bit.GPIO34 = 1; // peripheral explorer: LED LD3 at GPIO34
    GpioCtrlRegs.GPBDIR.bit.GPIO49 = 1; // peripheral explorer: LED LD4 at GPIO49

    GpioCtrlRegs.GPCDIR.all = 0;        // Set GPIO 87-64 to defaults
    EDIS;
}
